//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by demo.rc
//
#define IDB_PNG1                        101
#define IDB_PNG2                        102
#define IDB_PNG3                        103
#define IDB_PNG4                        104
#define IDB_PNG5                        105
#define IDR_WAV_HOVER                   106
#define IDR_WAV_CLICK                   107
#define IDR_WAVE_OPEN_INV               108
#define IDR_WAVE_CLOSE_INV              109
#define IDR_STEP_D1                     110
#define IDR_STEP_D2                     111
#define IDR_STEP_D3                     112
#define IDR_STEP_D4                     113
#define IDR_STEP_L1                     114
#define IDR_STEP_L2                     115
#define IDR_STEP_L3                     116
#define IDR_STEP_L4                     117
#define IDR_STEP_M1                     119
#define IDR_STEP_M2                     120
#define IDR_STEP_M3                     121
#define IDR_STEP_M4                     122
#define IDR_STEP_M5                     123
#define IDR_STEP_DIR1                   124
#define IDR_STEP_DIR2                   125
#define IDR_STEP_DIR3                   126
#define IDR_STEP_DIR4                   127
#define IDR_STEP_DIR5                   128
#define IDR_STEP_C1                     129
#define IDR_STEP_C2                     130
#define IDR_STEP_C3                     131
#define IDR_STEP_C4                     132
#define IDR_STEP_V1                     133
#define IDR_STEP_V2                     134
#define IDR_STEP_V3                     135
#define IDR_STEP_V4                     136
#define IDR_TERMINAL_DENIED             138
#define IDR_TERMINAL_GRANTED            139
#define IDR_SHOP_BUY                    140
#define IDR_WAV_ERROR                   141
#define IDR_CARD_DRAW1                  145
#define IDR_CARD_DRAW2                  146
#define IDR_CARD_DRAW3                  147
#define IDR_CARD_DRAW4                  148
#define IDR_HURT1                       149
#define IDR_HURT2                       150
#define IDR_HURT3                       151
#define IDR_HURT4                       152
#define IDR_HURT5                       153
#define IDR_PLAYER_DEAD                 154
#define IDR_COIN_GATHER                 155
#define IDR_CARD_SNAP                   156
#define IDR_CARD_SNAP2                  157
#define IDR_POWERUP1                    158
#define IDR_DIALOG_VOICE1               159
#define IDR_DIALOG_VOICE2               160
#define IDR_DIALOG_VOICE3               161
#define IDR_DIALOG_VOICE4               162
#define IDR_DIALOG_VOICE5               163
#define IDR_POWERUP2                    164
#define IDR_POWERUP3                    165
#define IDR_CHECKPOINT                  166
#define IDR_BGM_ARCADE                  167
#define IDR_BGM_SKY                     169
#define IDR_BGM_TUTORIAL                171
#define IDR_BGM_BAT_BOSS                172
#define IDR_BGM_B1                      173
#define IDR_BGM_B2                      174
#define IDR_BGM_B3                      175
#define IDR_BGM_B4                      176
#define IDR_BGM_BOSS                    177
#define IDR_BGM_SECRET                  178
#define IDR_CARD_DRAW5                  179
#define IDR_CARD_SNAP3                  180
#define IDR_CARD_SNAP4                  181
#define IDR_TOKEN_COLLECT1              182
#define IDR_TOKEN_COLLECT2              183
#define IDR_TOKEN_COLLECT3              184
#define IDR_TOKEN_COLLECT4              185
#define IDR_TOKEN_COLLECT5              186
#define IDR_TOKEN_COLLECT6              187
#define IDR_TOKEN_SPAWN1                188
#define IDR_TOKEN_SPAWN2                189
#define IDR_TOKEN_SPAWN3                190
#define IDR_TOKEN_SPAWN4                191
#define IDR_BLEEP1                      192
#define IDR_BLEEP2                      193
#define IDR_BLEEP3                      194
#define IDR_BLEEP4                      195
#define IDR_BLEEP5                      196
#define IDR_BLEEP6                      197
#define IDR_BLEEP7                      198
#define IDR_BLEEP8                      199
#define IDR_BLEEP9                      200
#define IDR_BLEEP10                     201
#define IDR_BLEEP11                     202
#define IDR_BLEEP12                     203
#define IDR_BLEEP13                     204
#define IDR_BLEEP14                     205
#define IDR_BLEEP15                     206
#define IDR_BLEEP16                     207
#define IDR_BLEEP17                     208
#define IDR_BLEEP18                     209
#define IDR_BLEEP19                     210
#define IDR_BLEEP20                     211
#define IDR_BLEEP21                     212
#define IDR_BLEEP22                     213
#define IDR_BLEEP23                     214
#define IDR_BLEEP24                     215
#define IDR_BLEEP25                     216
#define IDR_BLEEP26                     217
#define IDR_BLEEP27                     218
#define IDR_BLEEP28                     219
#define IDR_BLEEP29                     220
#define IDR_BLEEP30                     221
#define IDR_QUEST_ACTIVE                       222
#define IDR_QUEST_COMPLETED                       223
#define IDR_BGM_BOSSWORLD_BASE                         224
#define IDR_BGM_BOSSWORLD_ISLAND12                     225
#define IDR_BGM_BOSSWORLD_ISLAND3                      226
#define IDR_BGM_BOSSWORLD_ISLAND4                      227

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        228
#define _APS_NEXT_COMMAND_VALUE         40002
#define _APS_NEXT_CONTROL_VALUE         1001
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
